-- Migration: Create nutrition_entries table
-- Replaces the 'nutrition_log' KV key (format: {date: {entries: [...]}})
--
-- Run this in Supabase SQL Editor before deploying the updated nutrition.py

CREATE TABLE IF NOT EXISTS nutrition_entries (
    id        TEXT        PRIMARY KEY,          -- short UUID (8 chars) generated by app
    date      DATE        NOT NULL,
    nom       TEXT        NOT NULL,
    calories  INTEGER     NOT NULL DEFAULT 0,
    proteines REAL        NOT NULL DEFAULT 0,
    glucides  REAL        NOT NULL DEFAULT 0,
    lipides   REAL        NOT NULL DEFAULT 0,
    heure     TEXT,                             -- HH:MM, set at insertion time
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS nutrition_entries_date_idx ON nutrition_entries (date DESC);

-- Enable Row Level Security (match other tables)
ALTER TABLE nutrition_entries ENABLE ROW LEVEL SECURITY;

-- Allow all operations for authenticated users (adjust to your RLS policy)
CREATE POLICY "nutrition_entries_all" ON nutrition_entries
    FOR ALL USING (true) WITH CHECK (true);
