# db.py — thin re-exporter facade
# All business logic lives in the sub-modules below.
# This file re-exports everything so that callers using `import db as _db`
# or `from db import <name>` continue to work unchanged.
#
# IMPORTANT: shared mutable state (_client, MODE, etc.) is owned by db_core.
# Access it only via `import db_core; db_core._client` — never via
# `from db_core import _client` which creates a stale snapshot.
from __future__ import annotations

# ── Core (shared state + SQLite helpers) ──────────────────────────────────────
import db_core

# Re-export module-level globals so `from db import _client` keeps working
from db_core import (
    MODE,
    _client,
    _ON_VERCEL,
    _SQL_LOCK,
    _CONN,
    logger,
    _now_iso,
    _ensure_sqlite,
    _reconnect,
    _is_disconnect,
    _sqlite_get,
    _sqlite_set,
    _sqlite_all_dirty,
    ensure_schema_migrations,
)

# ── Exercises ─────────────────────────────────────────────────────────────────
from db_exercises import (
    get_exercises,
    get_exercise_by_name,
    get_exercise_id,
    update_program_scheme_for_exercise,
    get_exercise_id_include_deleted,
    get_or_create_exercise_id,
    upsert_exercise,
    rename_exercise_table,
    delete_exercise_by_name,
)

# ── Sessions & Exercise logs ──────────────────────────────────────────────────
from db_sessions import (
    get_workout_sessions,
    get_total_session_count,
    get_all_time_volume_lbs,
    get_session_streaks,
    get_workout_session,
    get_or_create_workout_session,
    get_workout_session_second,
    get_or_create_workout_session_second,
    get_workout_session_bonus,
    get_or_create_workout_session_bonus,
    create_workout_session,
    complete_workout_session,
    complete_workout_session_bonus,
    update_workout_session_bonus,
    delete_workout_session_by_type,
    delete_exercise_logs_for_session,
    upsert_exercise_log_direct,
    get_exercise_history_grouped_by_session,
    update_workout_session_by_type,
    update_workout_session,
    delete_workout_session,
    get_exercise_history,
    get_all_exercise_history,
    get_exercise_history_bulk,
    get_session_exercise_logs,
    get_previous_session_by_name,
    get_workout_session_by_type,
    get_exercise_logs_for_session_with_names,
    get_exercise_logs_since,
    get_previous_session_by_exercises,
    get_previous_session_of_type,
    get_exercise_info,
    get_exercises_info_bulk,
    update_exercise_default_scheme,
    normalize_schemes_max_sets,
    bulk_set_rest_seconds,
    upsert_exercise_log,
    upsert_exercise_log_by_type,
    delete_exercise_log_entry,
    delete_exercise_log_entry_by_type,
    bulk_upsert_exercise_logs,
    bulk_apply_session_exercise_patches,
    delete_session_exercise_logs,
    INT_FIELDS,
    DECIMAL_FIELDS,
)

# ── Body ──────────────────────────────────────────────────────────────────────
from db_body import (
    get_body_weight_logs,
    upsert_body_weight,
    log_body_weight_wearable,
    delete_body_weight,
    get_hiit_logs,
    insert_hiit_log,
    update_hiit_log,
    delete_hiit_log_by_id,
    get_recovery_logs,
    upsert_recovery_log,
    merge_recovery_wearable,
    delete_recovery_log,
    get_goals,
    set_goal,
    get_cardio_logs,
    insert_cardio_log,
    delete_cardio_log,
)

# ── Profile ───────────────────────────────────────────────────────────────────
from db_profile import (
    get_profile,
    update_profile,
    get_coach_memory,
    save_coach_memory,
    get_nutrition_settings,
    update_nutrition_settings,
    get_nutrition_entries,
    insert_nutrition_entry,
    update_nutrition_entry,
    delete_nutrition_entry,
    get_nutrition_entries_recent,
    get_hydration_today,
    log_hydration,
    get_food_catalog,
    save_food_catalog,
    get_meal_templates,
    create_meal_template,
    update_meal_template,
    delete_meal_template,
    get_deload_state,
    set_deload_state,
)

# ── Programs ──────────────────────────────────────────────────────────────────
from db_programs import (
    get_all_programs,
    get_full_program,
    save_full_program,
    create_program,
    rename_program,
    delete_program,
    delete_program_session,
    reorder_program_sessions,
    get_active_program_id,
    set_active_program_id,
    get_default_program_id,
    get_relational_week_schedule,
    set_relational_week_schedule,
    get_evening_week_schedule,
    set_evening_week_schedule,
    get_all_session_names,
    get_session_supersets,
    get_session_override,
    set_session_override,
    get_cycle_start_date,
    set_cycle_start_date,
)

# ── Wellness ──────────────────────────────────────────────────────────────────
from db_wellness import (
    get_mood_logs,
    insert_mood_log,
    get_pss_records,
    insert_pss_record,
    get_sleep_records,
    upsert_sleep_record,
    delete_sleep_record,
    get_journal_entries_all,
    insert_journal_entry,
    count_journal_entries_since,
    search_journal_entries_db,
    get_breathwork_sessions,
    insert_breathwork_session,
    get_self_care_habits,
    upsert_self_care_habit,
    delete_self_care_habit,
    get_self_care_log,
    set_self_care_log_for_date,
    get_life_stress_score_db,
    upsert_life_stress_score,
    get_coach_history,
    insert_coach_message,
    get_goals_archived,
    add_goal_archived,
    remove_goal_archived,
    update_exercise_current_weight,
    get_sessions_for_correlations,
    get_smart_goals,
    upsert_smart_goal,
    delete_smart_goal,
    compute_smart_goal_current,
    compute_smart_goal_progress,
    SMART_GOAL_META,
    get_latest_generated_program,
    save_generated_program,
    update_generated_program,
)

# ── Stats / Analytics ─────────────────────────────────────────────────────────
from db_stats import (
    get_weekly_tonnage,
    get_pattern_volume,
    get_programme_compliance,
    get_one_rm_trend,
    get_hiit_completion,
    get_nutrition_daily_full,
    get_macros_by_day_type,
    get_protein_weight_ratio,
    get_mood_trend,
    _get_session_volume_map,
    get_soreness_volume_scatter,
    get_sleep_volume_scatter,
    get_rpe_progression,
    get_rir_by_exercise,
    get_self_care_compliance,
    get_self_care_streaks_computed,
    get_pain_journal,
    get_sessions_with_energy_pre,
    get_exercise_logs_with_category,
)

# ── Features (Ritual, War Room, Spirit, Oath, Seasons) ────────────────────────
from db_features import (
    get_ritual_today,
    upsert_ritual,
    get_ritual_history,
    get_ritual_demons,
    get_ritual_history_full,
    count_ritual_entries,
    get_war_room_config,
    upsert_war_room_config,
    get_war_room_battles,
    upsert_war_room_battle,
    get_war_room_triggers,
    insert_war_room_trigger,
    get_war_room_arsenal,
    insert_war_room_arsenal_item,
    delete_war_room_arsenal_item,
    increment_arsenal_use,
    get_spirit_config,
    upsert_spirit_config,
    log_breathwork_session,
    get_breathwork_sessions as get_breathwork_sessions_spirit_alias,
    log_meditation_session,
    get_meditation_sessions,
    save_spirit_journal_entry,
    get_spirit_journal_entries,
    get_spirit_journal_entry,
    get_current_oath,
    get_oath_versions,
    save_oath,
    log_oath_recall,
    get_oath_recalls,
    get_breathwork_sessions_spirit,
    get_next_season_number,
    get_active_season,
    get_all_seasons,
    get_season_by_id,
    create_season,
    save_season_snapshot,
    close_season,
    update_season,
    get_season_snapshots,
    get_prev_season_had_reset,
    get_spirit_metadata,
    get_war_room_coach_context,
    _next_month_str,
    get_adherence_active_days,
    get_current_1rm_estimates,
    get_coach_war_room_shared,
    set_coach_war_room_shared,
    upsert_body_budget_log,
    get_body_budget_recent,
)
